version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: voltage_postgres
    restart: always
    environment:
      POSTGRES_USER: voltage
      POSTGRES_PASSWORD: voltage123
      POSTGRES_DB: voltagedb
    ports:
      - "5439:5432"
    volumes:
      - voltage_pgdata:/var/lib/postgresql/data

volumes:
  voltage_pgdata:
